# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  - test-coverage:
          description: |
              Test Coverage
          executor:
              name: default
              tag: "15.1"
          steps:
              - checkout
              - install-packages:
                  app-dir: ~/project
                  cache-version: v1
                  override-ci-command: ""
                  pkg-manager: npm
              - run:
                  command: npm run coverage
                  name: Run NPM Tests
                  working_directory: ~/project

workflows:
  sample:
    jobs:
      - node/test:
          version: "15.1"
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
      - test-coverage: